name: Black Formatter
description: ''
runs:
  using: composite
  steps:
  - name: Black Formatter
    shell: bash
    run: |
        python -m pip install --upgrade pip
        pip install black
        black .